name = "shiftflow"
compatibility_date = "2025-11-02"
pages_build_output_dir = "frontend/public"

[[d1_databases]]
binding = "DB"
database_name = "app_d1_dev"
database_id = "6ed349e4-06e1-4eab-b850-b2b99450bfda"

[[kv_namespaces]]
binding = "APP_KV"
id = "8d1cb20b32c3432d88944d3981b4275a"

[[r2_buckets]]
binding = "R2"
bucket_name = "app-r2-dev"

[env.preview]
[[env.preview.d1_databases]]
binding = "DB"
database_name = "app_d1_dev"
database_id = "6ed349e4-06e1-4eab-b850-b2b99450bfda"

[[env.preview.kv_namespaces]]
binding = "APP_KV"
id = "8d1cb20b32c3432d88944d3981b4275a"

[[env.preview.r2_buckets]]
binding = "R2"
bucket_name = "app-r2-dev"

[env.production]
[[env.production.d1_databases]]
binding = "DB"
database_name = "app_d1_prod"
# TODO: update to the real production D1 database_id
database_id = "2a9b6101-3c1c-400a-bd3d-f19a8e8d103e"

[[env.production.kv_namespaces]]
binding = "APP_KV"
id = "7c68c6152a1541dd83c2415a61333db3"

[[env.production.r2_buckets]]
binding = "R2"
bucket_name = "app-r2-prod"
